# Generated by Django 4.2.10 on 2024-02-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(blank=True, max_length=100, null=True)),
                ('option_image', models.ImageField(blank=True, null=True, upload_to='OptionImages')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserSide.category')),
            ],
        ),
    ]
