# Generated by Django 4.2.10 on 2024-02-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSide', '0003_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='DishImages/')),
                ('dish_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_price', models.FloatField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSide.category')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserSide.option')),
            ],
        ),
    ]
